### ISSUE TITLE
Add a usage

### ISSUE THREAD

**Issue by pickfire** [esn89/base16-zathura#1]

**Comment by esn89** [comment]
a usage?

**Comment by pickfire** [comment]
Maybe something like location to let people quickly add the file into the location. _Quick Installation_

**Comment by esn89** [comment]
Ooooh.  Okay, I see what you mean, I can definitely do that.

**Comment by esn89** [comment]
done with the latest commit.  cheers

**Comment by pickfire** [comment]
Good luck and have a nice day!
